name: tailscale-ssh
on:
  workflow_dispatch:

jobs:
  code-test:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Remove unwanted stuff
        uses: gbraad-devenv/remove-unwanted@v1
      - name: Run system container with `podman`
        run: |
          podman run -d --name steamcmd \
            --cap-add=NET_ADMIN --cap-add=NET_RAW --device=/dev/net/tun \
            ghcr.io/gbraad-gaming/steamcmd:latest
      - name: Tailscale setup (root)
        run: |
          until podman exec steamcmd tailscale up --auth-key ${TAILSCALE_AUTHKEY} \
            --ssh --hostname github-${HOSTNAME}
          do
              sleep 0.1
          done
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY}}
      - name: Hang around
        run: |
          until podman exec steamcmd systemctl is-active --quiet tailscaled
          do
               sleep 1
          done
          IP=`podman exec steamcmd tailscale ip -4`
          echo "Use the following command to connect \`tailscale ssh gbraad@${IP}\`"
          sleep infinity